# permissions for end users to view integrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integration-viewer-role
rules:
- apiGroups:
  - uniform.my.domain
  resources:
  - integrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - uniform.my.domain
  resources:
  - integrations/status
  verbs:
  - get
