# permissions for end users to edit integrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integration-editor-role
rules:
- apiGroups:
  - uniform.my.domain
  resources:
  - integrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uniform.my.domain
  resources:
  - integrations/status
  verbs:
  - get
