apiVersion: uniform.my.domain/v1alpha1
kind: Integration
metadata:
  name: integration-sample
  namespace: keptn
spec:
  # Add fields here
  name: "job-executor-service"
  image: "keptnsandbox/job-executor-service:0.1.1"
  events:
    - "sh.keptn.event.deployment.triggered"

  remote:
    apiURL: "my-api-url"
    apiToken:
      fromSecret:
        secretName: "keptn-api-token"
        field: "keptn-api-token"
  env:
    - name: INIT_CONTAINER_CONFIGURATION_SERVICE_API_ENDPOINT
      value: "http://localhost:8081/configuration-service"
    - name: CONFIGURATION_SERVICE
      value: 'http://localhost:8081/configuration-service'
    - name: JOB_NAMESPACE
      value: 'keptn'
    - name: INIT_CONTAINER_IMAGE
      value: 'keptnsandbox/job-executor-service-initcontainer:0.1.1'
